// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoi1Zq5sEim07RSh9JlwcernXpOvE2JkE',
    appId: '1:480486382429:web:fb71dd0ad78bda5c9aa6b4',
    messagingSenderId: '480486382429',
    projectId: 'presences-app',
    authDomain: 'presences-app.firebaseapp.com',
    storageBucket: 'presences-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASlvy0yNdXtTqbKF0HruCPQypyqukOIqI',
    appId: '1:480486382429:android:44b0ee59977495b79aa6b4',
    messagingSenderId: '480486382429',
    projectId: 'presences-app',
    storageBucket: 'presences-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNii1FY3rBQC5G7E6RrPGGtG4C5dyBy_M',
    appId: '1:480486382429:ios:fcec9b05f013c6de9aa6b4',
    messagingSenderId: '480486382429',
    projectId: 'presences-app',
    storageBucket: 'presences-app.appspot.com',
    iosBundleId: 'id.navetacandra.presence',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNii1FY3rBQC5G7E6RrPGGtG4C5dyBy_M',
    appId: '1:480486382429:ios:fcec9b05f013c6de9aa6b4',
    messagingSenderId: '480486382429',
    projectId: 'presences-app',
    storageBucket: 'presences-app.appspot.com',
    iosBundleId: 'id.navetacandra.presence',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoi1Zq5sEim07RSh9JlwcernXpOvE2JkE',
    appId: '1:480486382429:web:dcf802d699398c2e9aa6b4',
    messagingSenderId: '480486382429',
    projectId: 'presences-app',
    authDomain: 'presences-app.firebaseapp.com',
    storageBucket: 'presences-app.appspot.com',
  );
}
